### ISSUE TITLE
ACCESSIBILITY: Fix links and h3 in footer

### ISSUE THREAD

**Issue by plang-psm** [plang-psm/popflix-v2#16]
Overview
From lighthouse report.

Links do not have a discernible name
- Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users. [Learn how to make links accessible](https://dequeuniversity.com/rules/axe/4.8/link-name).

Heading elements are not in a sequentially-descending order
- Properly ordered headings that do not skip levels convey the semantic structure of the page, making it easier to navigate and understand when using assistive technologies. [Learn more about heading order](https://dequeuniversity.com/rules/axe/4.8/heading-order).

Action Items
- [ ] Fix social tags found in the footer file
- [ ] Fix h3 header in footer
     - `<h3 class="text-md ">Designed and developed by plang-psm</h3>`
- [ ] Test and apply
- [ ] Include lighthouse test screenshot in PR

Resources/Instructions
N/A

**Comment by kiranrega** [comment]
Hello @plang-psm , I would like work on this issue, can you please assign it to me. and share me the process to set it up locally. Thank you
